name: randykelley
favicon: null
layout_spectrum: 0.522966178599745
typography_spectrum: 0.22003793553449214
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.3161280886270106
  lightness: 0.6380271576344967
  saturation: 0.5108940715435892
  rhythmicContrast: 0.3332083276472986
purpose: []
